### ISSUE TITLE
Modrinth: fetching wrong game version

### ISSUE THREAD

**Issue by MiniCheese26** [itzg/mc-image-helper#152]
Mods downloaded from Modrinth are no longer respecting the MC version supplied. I think it's to do with https://github.com/itzg/mc-image-helper/pull/151 which made a change to the `game_versions` query argument.

I ran https://github.com/itzg/docker-minecraft-server/ with the DEBUG arg on and when it hits `https://api.modrinth.com/v2/project/P7dR8mSH/version?loaders=fabric&game_versions=1.19.2` it fails, but if I change `game_versions=1.19.2` to `game_versions=["1.19.2"]` it now works correctly. It's the same for the loaders arg as well.

Not sure what's going on with their API.

**Comment by itzg** [comment]
Ugh, that is very frustrating. As you saw, I just changed that to **fix their API being broken** when using quoted arrays. I guess I'll put it back and report an issue with them. Or maybe it's the launcher arg that changed from documented behavior. 

If you could help investigate the originally reported issue, then that would be much appreciated 

https://github.com/itzg/docker-minecraft-server/issues/1973

**Comment by itzg** [comment]
Oh! The original issue is because `paper` needs to be referenced specifically as the loader and not assume that it falls under the spigot family.

This is going to get messy having to try one and then other loader 🤦‍♂️
