### ISSUE TITLE
Cannot find version in older FORGE_INSTALLER

### ISSUE THREAD

**Issue by kevinkjt2000** [itzg/mc-image-helper#174]
```
[mc-image-helper] 15:03:24.262 ERROR : 'install-forge' command failed. Version is 1.25.16
 me.itzg.helpers.errors.GenericException: Failed to locate version from provided installer file
        at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:88)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:84)
        at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:16)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:132)
[init] ERROR failed to install Forge given installer /modpacks/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar
```

**Comment by kevinkjt2000** [comment]
Thanks for the helpful DEVELOPMENT.md documentation. I was able to easily reproduce this with `./gradlew run --info --args="install-forge --forge-installer=./forge-1.7.10-10.13.4.1614-1.7.10-installer.jar --output-directory=./tmp"`

I'm taking a look at the Java source code now to see if there's an easy fix.

**Comment by itzg** [comment]
Thanks for reporting/investigating. What it's doing now is looking for a manifest inside the jar file. Use unzipping tool to see if the older forge jars have a similar manifest that could be discovered and processed.

**Comment by itzg** [comment]
I couldn't help investigating some more. It's because the `id` is formatted a bit different with

```
  "id": "1.7.10-Forge10.13.4.1614-1.7.10",
```

where the second position was expected to be just "forge". I can fix this pretty easily.

**Comment by kevinkjt2000** [comment]
I found that there is no version.json file in the installer file I have. So I opened a PR with a fallback to using parts of the filename itself.

**Comment by itzg** [comment]
Yeah, I was mistaken by looking at the resulting "universal jar".

**Comment by itzg** [comment]
`install_profile.json` seems to be usable with:

```json
{
  "install": {
    "profileName": "Forge",
    "target": "1.7.10-Forge10.13.4.1614-1.7.10",
    "path": "net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10",
    "version": "Forge 10.13.4.1614-1.7.10",
    "filePath": "forge-1.7.10-10.13.4.1614-1.7.10-universal.jar",
    "welcome": "Welcome to the simple Forge installer.",
    "minecraft": "1.7.10",
    "mirrorList": "https://files.minecraftforge.net/mirror-brand.list",
    "logo": "/big_logo.png"
  },
  "versionInfo": {
    "id": "1.7.10-Forge10.13.4.1614-1.7.10",
```

**Comment by kevinkjt2000** [comment]
Hmmm that might be better to process then. Let me try an even older version of forge to see if that install_profile.json is still there. And I'll parse the version info this way instead. Depending on the filename is flaky if a user was to rename it.

**Comment by itzg** [comment]
I'm already finished with the fix.

**Comment by kevinkjt2000** [comment]
Awww I tried to contribute :cry: 
But yay it's fixed! :confetti_ball:

**Comment by itzg** [comment]
Sorry, to rush ahead of you. It was one of those where by the time I investigated more I pretty much had it solved.

**Comment by kevinkjt2000** [comment]
Should I raise new bugs since that other one already merged? I was starting to leave review comments. I also pushed my own implementation that I had tested.

**Comment by itzg** [comment]
Were there bugs with it? Go ahead and leave comments and I'll take it from there.
