### ISSUE TITLE
Add support for single CurseForge mods

### ISSUE THREAD

**Issue by ThallesP** [itzg/mc-image-helper#268]
As now the tool seems to only supports modpacks and not single mods, for example:

https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway - I get "Unexpected URL structure"

adding support for this could be done by removing the static `classId` for modpacks and changing the `PAGE_URL_PATTERN` regex, the curseforge api response seems to be same. (this is just a guess)

**Comment by itzg** [comment]
Related to #2293

...both of which I thought duplicated an existing issue, but I realized it was my deprecation notice I put [here](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/forge-api/#forge-api) that I'm thinking of.
