### ISSUE TITLE
Pls make work with bedrock

### ISSUE THREAD

**Issue by badwolfunit** [itzg/mc-image-helper#496]
I am planning on opening a bedrock server with my friends and that will descend into chaos quickly so this would be useful

**Comment by itzg** [comment]
I don't understand what you're asking for. Maybe you posted on the wrong repo and meant to post on https://github.com/itzg/docker-minecraft-bedrock-server

**Comment by badwolfunit** [comment]
Sorry I meant to post this on the mc-back-up page

**Comment by itzg** [comment]
That makes sense now. In that case refer to this section for backup options https://github.com/itzg/docker-minecraft-bedrock-server#community-solutions

**Comment by badwolfunit** [comment]
Thanks sorry for posting this on the wrong repo
