### ISSUE TITLE
modrinth: support per project version type declaration

### ISSUE THREAD

**Issue by itzg** [itzg/mc-image-helper#74]
Also, allow for projects to be split by whitespace only.

Originally suggested at https://github.com/itzg/docker-minecraft-server/issues/1871

**Comment by michiruf** [comment]
Another  suggestion could be, to specify the specific version of a mod, because if things run properly, you may do not want to update those (I myself am pretty much always specifying explicit versions)

**Comment by itzg** [comment]
Yep, I was thinking/assuming the same

**Comment by JustMangoT** [comment]
Except for ``whitespace`` feature, I think this can be closed
